# /etc/wireguard/wg0.conf for bkk08
# wireguard vpn to bkk00 management network

[Interface]
Address = 172.31.0.8/16
PrivateKey = <PASTE_FROM_/etc/wireguard/privatekey>

[Peer]
# bkk00 - vpn hub
PublicKey = gkXioj9pgmNULmvJqN9LtR31XaCfVWF/11QHxJBYhTg=
Endpoint = 10.155.108.0:51820
AllowedIPs = 172.31.0.0/16
PersistentKeepalive = 25

[Peer]
# bkk20 - backup vpn hub
PublicKey = /09ofEbIM1qjlq7xM/R0KfJMQ8R/UR9aHaph70FTp30=
Endpoint = 10.155.208.0:51820
AllowedIPs = 172.31.0.20/32
PersistentKeepalive = 25

[Peer]
# bkk50 - validator router
PublicKey = HSEVRjXj7x7jSVy8A9YQducW6BNme/a19/o5CA/KrUI=
Endpoint = 10.155.255.3:52180
AllowedIPs = 172.31.0.50/32
PersistentKeepalive = 25
