# /etc/wireguard/wg0.conf for bkk12 (validator)
# wireguard vpn to bkk00 management network

[Interface]
Address = 172.31.0.12/16
PrivateKey = <PASTE_FROM_/etc/wireguard/privatekey>

[Peer]
# bkk00 - vpn hub
PublicKey = gkXioj9pgmNULmvJqN9LtR31XaCfVWF/11QHxJBYhTg=
Endpoint = 172.16.10.1:51820
AllowedIPs = 172.31.0.0/16
PersistentKeepalive = 25

[Peer]
# bkk20 - backup vpn hub
PublicKey = /09ofEbIM1qjlq7xM/R0KfJMQ8R/UR9aHaph70FTp30=
Endpoint = 160.22.181.178:51820
AllowedIPs = 172.31.0.20/32
PersistentKeepalive = 25
