name: Daily Mikrotik Config Export

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at 12 AM UTC
  workflow_dispatch:

jobs:
  export-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        env:
          BKK00_KEY: ${{ secrets.BKK00_SSH_KEY }}
          # BKK10_KEY: ${{ secrets.BKK10_SSH_KEY }}
          # BKK20_KEY: ${{ secrets.BKK20_SSH_KEY }}
          # BKK50_KEY: ${{ secrets.BKK50_SSH_KEY }}
          # BKK60_KEY: ${{ secrets.BKK60_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "$BKK00_KEY" > ~/.ssh/bkk00
          # echo "$BKK10_KEY" > ~/.ssh/bkk10
          # echo "$BKK20_KEY" > ~/.ssh/bkk20
          # echo "$BKK50_KEY" > ~/.ssh/bkk50
          # echo "$BKK60_KEY" > ~/.ssh/bkk60

          chmod 600 ~/.ssh/bkk*

      - name: Export configs
        run: |
          echo "=== Exporting config from bkk00 ==="
          ssh -i ~/.ssh/bkk00 -o StrictHostKeyChecking=no bkk00@status.rotko.net | tee bkk00.rsc
          echo "=== Export completed ==="
          echo "=== Preview of saved file ==="
          head -n 20 bkk00.rsc
          # ssh -i ~/.ssh/bkk00 -o StrictHostKeyChecking=no bkk00@status.rotko.net '/export terse hide-sensitive' > bkk00.rsc
          # ssh -i ~/.ssh/bkk10 -o StrictHostKeyChecking=no admin@bkk10 '/export terse hide-sensitive' > bkk10.rsc
          # ssh -i ~/.ssh/bkk20 -o StrictHostKeyChecking=no admin@bkk20 '/export terse hide-sensitive' > bkk20.rsc
          # ssh -i ~/.ssh/bkk50 -o StrictHostKeyChecking=no admin@bkk50 '/export terse hide-sensitive' > bkk50.rsc
          # ssh -i ~/.ssh/bkk60 -o StrictHostKeyChecking=no admin@bkk60 '/export terse hide-sensitive' > bkk60.rsc

      # - name: Commit and push
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git add *.rsc
      #     git commit -m "Daily config export"
      #     git push || echo "Nothing to commit"
